# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iSport' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iSport
  pod 'UICircularProgressRing'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'SideMenuSwift'
  pod 'MessageKit'
  pod 'Scaledrone', '~> 0.3.0'
  pod 'GTProgressBar'

  target 'iSportTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iSportUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
